version: "3.9"
services:
  postgresql:
    image: "public.ecr.aws/docker/library/postgres:15.2"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  redis:
    image: "public.ecr.aws/docker/library/redis:7.0"
    ports:
      - "6379:6379"
    restart: always
volumes:
  pgdata:
