openapi: 3.1.0
info:
  title: COWAY America Example API
  version: '1.0'
  summary: example
  description: 미신사 프로젝트용 백엔드 API 예시 문서 입니다.
  contact:
    name: IT서비스개발팀
servers:
  - description: Local
    url: 'http://localhost:8080'
tags:
  - name: example
paths:
  /comments:
    post:
      summary: 댓글 목록 조회
      operationId: post-comments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/default-response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/comment-list-item'
                    required:
                      - data
      description: 댓글 목록을 조회하기 위한 API Endpoint 입니다.
      security:
        - oauth2_access_token: []
      tags:
        - example
  /comment:
    post:
      summary: 댓글 입력
      operationId: post-comment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/default-response'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/comment-detail-item'
      description: 댓글 생성을 위한 API Endpoint 입니다.
      security:
        - oauth2_access_token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contents:
                  type: string
                  description: 댓글 내용
              required:
                - contents
      tags:
        - example
  '/comment/{commentId}':
    parameters:
      - schema:
          type: string
        name: commentId
        in: path
        required: true
        description: 댓글 식별자
    get:
      summary: 댓글 조회
      tags:
        - example
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/default-response'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/comment-detail-item'
      operationId: get-comment-commentId
      description: 댓글 상세 조회를 위한 API Endpoint 입니다.
      security:
        - oauth2_access_token: []
    put:
      summary: 댓글 수정
      operationId: put-comment-commentId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/default-response'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/comment-detail-item'
                    required:
                      - data
      security:
        - oauth2_access_token: []
      description: 댓글 수정을 위한 API Endpoint 입니다.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contents:
                  type: string
                  description: 수정 댓글 내용
              required:
                - contents
      tags:
        - example
    delete:
      summary: 댓글 삭제
      operationId: delete-comment-commentId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/default-response'
                  - type: object
                    properties:
                      data:
                        type:
                          - object
                          - 'null'
      description: 댓글 삭제를 위한 API Endpoint 입니다.
      security:
        - oauth2_access_token: []
      tags:
        - example
components:
  securitySchemes:
    oauth2_access_token:
      type: http
      scheme: bearer
  schemas:
    default-response:
      title: default-response
      x-stoplight:
        id: 85albri2i55r0
      type: object
      properties:
        code:
          type: string
          description: |-
            사전에 협의되고 정의된 API 처리 결과 코드 또는 오류 코드입니다.
            코드는 대문자 SNAKE_CASE 문자열로 표기합니다.
        message:
          type: string
          description: API 처리 결과에 대하여 사용자에 알려주는 메시지로 다국어 처리가 된 메시지 입니다.
          pattern: '^[A-Z0-9_]+$'
      required:
        - code
        - message
    comment-list-item:
      title: 댓글 목록 항목 모델
      type: object
      properties:
        id:
          type: string
          description: 댓글 식별자
        contents:
          type: string
          description: 댓글 내용
        viewCount:
          type: integer
          description: 댓글 조회 수
      required:
        - id
        - contents
        - viewCount
      description: 댓글 목록 항목
    comment-detail-item:
      title: 댓글 상세 항목 모델
      type: object
      properties:
        id:
          type: string
          description: 댓글 식별자
        contents:
          type: string
          description: 댓글 내용
        viewCount:
          type: integer
          description: 댓글 조회 수
        createdDateTime:
          type: string
          format: date-time
          description: 댓글 생성 일시
      required:
        - id
        - contents
        - viewCount
        - createdDateTime
  parameters: {}
